### ISSUE TITLE
Pulling into empty project doesn't work (creates all files but doesn't update them)

### ISSUE THREAD

**Issue by andrewmoise** [leonhartX/gas-github#102]
So I do the following:

* Create an empty Google Spreadsheet
* Name the spreadsheet
* Open the script editor
* Name the project so it saves
* Try to check out the project "oyd-daily", branch "prod_0_4", into the empty project (it's oyd-daily; it's a private project but I've shared it with you in case it's something in the project that's causing things to fail)

When I do that, it creates all the files successfully, then fails to actually update them (they're all left with "function myFunction() { }" as the entirety of the code).

I investigated a little bit (I love the extension, don't get me wrong, but it keeps giving me intermittent issues, and I've downloaded the code and started poking at it to see if I can fix or work around any of the things that are causing me problems). What's happening is that on line 187, in gasUpdateFile(), the RPC API is not giving us "//OK", but instead returning "//EX[2,1,".

I can poke around a little more but I thought I'd bring it up in case you know any more / can look into it. Thanks again for the extension.

-Andrew

**Comment by jolman-kg** [comment]
Seeing that same issue here too. Thanks for digging into this further Andrew! (I don't have anything productive to add here but I'll be watching closely.)

**Comment by leonhartX** [comment]
maybe some RPC change, going to check it soon.
also #103 seems related

**Comment by leonhartX** [comment]
fixed in v4.0.5
