### ISSUE TITLE
Push deletes the contents of all the files, but leaves files with "1F" in.

### ISSUE THREAD

**Issue by andrewroberts** [leonhartX/gas-github#103]
When I do a push to one of my dev branches the diff says it is removing most of the content and replacing it with a single "1F" char. I've followed through with the push and this is what actually gets pushed. I've tried it on a couple of different repos.

![image](https://user-images.githubusercontent.com/4705245/48192801-b17d6f80-e340-11e8-9a0a-d76757907785.png)

**Comment by mushuser** [comment]
same bug here

**Comment by mushuser** [comment]
Google offers Apps script REST API, https://developers.google.com/apps-script/api/reference/rest/ 
We can get the remote file instead of local html for git diff, which should prevent this issue.

**Comment by leonhartX** [comment]
fixed in v4.0.5

**Comment by leonhartX** [comment]
@mushuser yes use the api is more stable although it will make the extension require the google api auth.
I'll consider changing to the rest api if i got enough time, and any contribution is appreciated.
