### ISSUE TITLE
Switch to using clasp API maybe?

### ISSUE THREAD

**Issue by andrewmoise** [leonhartX/gas-github#104]
What do people think of the idea of switching to whatever API it is that clasp is using, instead of the (apparently undocumented and sort of volatile) RPC API we're currently using? I *love* what this extension does, but it seems like it's prone to flakiness as a sort of unavoidable consequence of going through the RPC API. I feel like it we migrated it to use the clasp API it would be solid and even more lovable.

**Comment by leonhartX** [comment]
as far as i know, clasp is for deploying a project to gas, it does nothing about scm. it just give you the possibility to manage code locally with anyway you like.
if you still want to use the online editor, there's no way to escape from the RPC

**Comment by andrewmoise** [comment]
Sure, I was just adding my vote because I'd been bitten by RPC-caused errors a couple of times (the failure if the name of the file is a function in the file, the RPC change from a couple of days ago)... I more or less switched to a different workflow to avoid having to use the plugin temporarily as a result. I like the plugin and it's extremely convenient, though, so I wanted to put in some advocacy for switching to a method of talking to the server that doesn't involve this occasional brokenness.

**Comment by leonhartX** [comment]
switched in 5.0.0
