### ISSUE TITLE
Gitlab Community Edition Support

### ISSUE THREAD

**Issue by TemperMichael** [leonhartX/gas-github#110]
It could be useful to support the gitlab community edition by letting the user enter an optional domain specific value: www.gitlab._example_.com 

Besides that, nice job with the add-on. It is really helpful, thank you 😊 👍

**Comment by leonhartX** [comment]
this has beed discussed here: #76 and #78 
since it will make the required permission become too ambiguous, currently I won't add this feature.

maybe release another version seems to be a solution.
