### ISSUE TITLE
How about something like this?

### ISSUE THREAD

**Issue by klausrheum** [leonhartX/gas-github#112]
Did you see the icon I made? No comments?

How about something like this?

![image](https://user-images.githubusercontent.com/45514331/49363296-e6989a00-f713-11e8-87ac-f30f0860c6bf.png)

Mocked up in Google Drawings - I can share you the doc but you can probably make something cleaner in Inkscape. I only have a Chromebook here!

https://docs.google.com/drawings/d/1UfnAdi_BlJC1mOdJmrx6Vk_52j-UDOeCq_Y_fd621ZM/edit?usp=sharing

_Originally posted by @klausrheum in https://github.com/leonhartX/gas-github/issues/89#issuecomment-443635112_

**Comment by leonhartX** [comment]
Oh sorry, I haven't noticed the comment.
Thanks, this looks awesome! 
I'll update the icon later

**Comment by leonhartX** [comment]
And can you make it a 128*128 size with transparent background?
I totally know nothing about drawing 😢

**Comment by klausrheum** [comment]
![gas-github_logo_128x128](https://user-images.githubusercontent.com/45514331/52951078-61885d00-33b3-11e9-8db9-f5301a9fcd44.png)

(I have edited the original doc linked in the first comment).

Klaus (aka John Kershaw).

**Comment by leonhartX** [comment]
Thanks!
Changed the icon.
