### ISSUE TITLE
How to ignore files?

### ISSUE THREAD

**Issue by derrickrc** [leonhartX/gas-github#128]
Hi, it seems that you've built support for ignore, but how do we implement it? Thank you.

**Comment by leonhartX** [comment]
click the config button (right next to the push button), you can add ignore pattern there
![image](https://user-images.githubusercontent.com/3993518/85481626-24625980-b5fd-11ea-9c0d-39afe75fec4d.png)

**Comment by derrickrc** [comment]
Thanks!
