### ISSUE TITLE
pull/push doesn't work when set 'Ignore file patterns *'

### ISSUE THREAD

**Issue by AkisueAtsushi** [leonhartX/gas-github#137]
When push/pull, I want to ignore some scripts whose filename starts with 'config', so I set 'ignore file pattern *' like this;

<img width="501" alt="スクリーンショット 2021-01-16 17 14 16" src="https://user-images.githubusercontent.com/10040652/104806924-57c93780-581e-11eb-945a-a04ca097f2ed.png">

but then pull/push icon(↑↓) doesn't work. nothing happened when click these icons.
and 'Warning log' popped up in console like this; 

<img width="555" alt="スクリーンショット 2021-01-16 17 11 38" src="https://user-images.githubusercontent.com/10040652/104806891-133d9c00-581e-11eb-93d9-95b03f71b9e7.png">

Is it bug thing ? or I miss any configurations or way to set 'ignore file pattern *' ?
I have no clue about this problem on any documents you published.

I'm using the latest version.(5.0.0)

Thank you in advance.

**Comment by leonhartX** [comment]
this is a known issue, fixed in #134 
but since Google is now taking a very long time to review I can not promise when it will be released (my last release has been pending review for more than 2 weeks and still can not release)

**Comment by AkisueAtsushi** [comment]
Thank you, then I'll wait the next release.
