### ISSUE TITLE
[github assistant] undefined error when pullng - PUT 400 error 

### ISSUE THREAD

**Issue by joapuiib** [leonhartX/gas-github#139]
I've logged with GitHub with no problems (I can see my repositories) and I've enabled AppScript API.
I've created a repository with a single file and I have been able to pull, but, when I've added a second file, I get `[github assistant] undefined`. I can see the diff dialog correctly.

Looking in the console, a PUT 400 error shows when I try to pull.

**Comment by ivangusev** [comment]
Addon's "pull" function stop to work. It shows **[github assistant] undefined** in console.

**Comment by marekcech** [comment]
same here is there a fix for this?????

**Comment by ivangusev** [comment]
@marekcech Have you tried to uninstall chrome addon and install again? For me the trick works.

**Comment by marekcech** [comment]
> @marekcech Have you tried to uninstall chrome addon and install again? For me the trick works.

thanks it helped, also i needed to regenerate token to new github token format, thanks

for everyone with same trouble
1) remove extension from chorme
2) install it again
3) regenerate token

**Comment by josep11** [comment]
Yes, for me regenerating the token and logging again worked.

Make sure to generate the Github Personal Access Token with **gist, repo** permissions

> > @marekcech Have you tried to uninstall chrome addon and install again? For me the trick works.
> 
> thanks it helped, also i needed to regenerate token to new github token format, thanks
> 
> for everyone with same trouble
> 
> 1. remove extension from chorme
> 2. install it again
> 3. regenerate token
> 4. login again, everything should work

**Comment by joapuiib** [comment]
Should I close this issue?
