### ISSUE TITLE
Console log error when running web app

### ISSUE THREAD

**Issue by edlisten** [leonhartX/gas-github#14]
For some reason your extension is causing an error to show up in the console log when I run a Web app.  Below is the error.

![error-jpg](https://cloud.githubusercontent.com/assets/6818639/20566742/34948130-b164-11e6-96c0-4ce2a1b82287.jpg)

**Comment by leonhartX** [comment]
@edlisten thanks for report this issue.
seems the web app and editor are having same url schema, so this page also triggered the extension.

**Comment by leonhartX** [comment]
@edlisten the extension has been update to v0.1.7 and won't causing any errors when open web app.
