### ISSUE TITLE
Can't push and pull

### ISSUE THREAD

**Issue by KoosKaas** [leonhartX/gas-github#149]
Hi @leonhartX !

Installed your extension. I can see repo's and branches. 
Execution log says: Notice	[github assistant] Repository updated
When I want to push or pull I get: Error	[github assistant] undefined

My (remote) developer says he can do push, but not pull.

Unclear what I need to do? Maybe I don't understand how to set it up.

Would be really great if we get your extension working. Looks like best solution to co-develop .gs scripts. 
Hope you can help us out. 

Thanks in advance!
Joost

**Comment by segmentseth** [comment]
I'm having the same problem--but only with pull.  I can push from one Scripts project, but when I try to pull that same code into another project, I get the same error.  Help please!

**Comment by segmentseth** [comment]
@KoosKaas found the answer in https://github.com/leonhartX/gas-github/issues/145. Looks like you need to enable the Apps Script API via https://script.google.com/home/usersettings.  Once I did this Pull worked perfectly, as did push.

**Comment by KoosKaas** [comment]
> @KoosKaas found the answer in #145. Looks like you need to enable the Apps Script API via https://script.google.com/home/usersettings. Once I did this Pull worked perfectly, as did push.

I already did that, but still got that issue.

 Seems like quite some people are effected by this issue. Unfortunately I don't have technical skills to help. If we are with many, maybe a joined sponsor effort can help?

**Comment by KoosKaas** [comment]
Yeah!! I solved the issue!!

The case in my specific situation is that I have a own google domain that I use. The account in that domain that I use for this extension is not my main account (with google admin rights). When I refreshed my script tab in chrome, it opened another tab where it wanted me to log in with my admin account. Before I refused to login. Once I logged in with my admin account, it worked :-)

(Not sure, but maybe it possible to give more rights in google admin to the 'sub' account that I use for GAS so the extension works right away).

**Comment by KoosKaas** [comment]
@leonhartX Your effort for developing the extension has been rewarderd via the sponsor link! Thanks! Great work!

**Comment by andrewroberts** [comment]
I tried the above solutions but could push, but not pull. I ended up just going back to the old IDE and installing [v4.0.7.](https://drive.google.com/file/d/1o2D4DM_sBGVDaHLBDZF6LPepqifcfuUQ/view?usp=sharing)

**Comment by wmgillett** [comment]
I had the same error  _[github assistant] undefined_ show up after having performed several successful pulls into a bounded Google Sheets script.  In my case, I closed the spreadsheet and script editor and reopened and the extension started working fine again.
