### ISSUE TITLE
Error in pulling/pushing

### ISSUE THREAD

**Issue by davidyang** [leonhartX/gas-github#15]
I can't push or pull - it looks like it's using getFileContent which may be deprecated?
 
The error I get in debugging is:

//EX[2,1,["com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException/3936916533","This application is out of date, please click the refresh button on your browser. ( Could not locate requested method \x27getFileContent(com.google.apps.maestro.server.frontend.common.shared.ProjectMetadata)\x27 in interface \x27com.google.apps.maestro.ide.shared.IdeService\x27 )"],0,7]

**Comment by leonhartX** [comment]
Yes, seesm google has updated the gwt methods. I'm working on it to make it compatible with the new gwt method.

**Comment by leonhartX** [comment]
@davidyang 
the extension has been update to 0.1.8 and works with new GAS method.

**Comment by davidyang** [comment]
Thanks for the fast response @leonhartX - that was awesome.  Thanks for making this - really a great workflow helper for developing container bound scripts.

Curious if you've used browserify or Typescript in your Apps Script?

**Comment by leonhartX** [comment]
@davidyang
>Curious if you've used browserify or Typescript in your Apps Script?

no, this was just wrote by pure javascript.

**Comment by plumSemPy** [comment]
@leonhartX seems this issue has surfaced again; response when trying to push: `"//EX[2,1,["com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException/3936916533","This application is out of date, please click the refresh button on your browser. ( Could not locate requested method \x27getFileContent(com.google.apps.maestro.server.frontend.common.shared.ProjectMetadata)\x27 in interface \x27com.google.apps.maestro.ide.shared.IdeService\x27 )"],0,7]"`

There does not seem to be any new gwt releases though

**Comment by leonhartX** [comment]
fixed in v4.0.4

**Comment by plumSemPy** [comment]
That is a pretty unexpected thing to do. But thank you very much for your fast response, unblocked me.
