### ISSUE TITLE
other browsers than Chrome?

### ISSUE THREAD

**Issue by cimenta** [leonhartX/gas-github#150]
Hi
I am looking for an easy way to commit my code to github. I found your Chrome extension. I work on different projects under different Google accounts so I am using Vivaldi and Brave at the same time. It seems tome that the extension is working only with Chrome. Is that right?

Are you planning to support other browsers like Brave or Vivaldi or any other?

Thank you
Radek

**Comment by leonhartX** [comment]
The old version can support other browsers, but the new version(5.x) only works with chrome since it use the chrome login feature.
