### ISSUE TITLE
Dropdowns for Repos and Branches not working after logging into SCM (new installation)

### ISSUE THREAD

**Issue by wmgillett** [leonhartX/gas-github#155]
After installing gas-github v5.0.5, opening up the IDE and  logging into SCM (bitbucket), I 
cannot seem to activate any of the dropdowns for Repo and Branch (or any other icon). 
Have seen no warnings and no requests for authorization from Chrome.
None of my subsequent troubleshooting has helped (reopening the browser, logging in and out of SCM, revoking the token and creating a new one, opening IDE on new blank spreadsheet, removing and reinstalling extension).  I also tried my github account and got the same results - able to login, but no access to Repo and Branch dropdowns.
I do have repos in both Bitbucket and Github.
I have at least 10 access tokens with other 3rd party apps that work fine.
What am I missing?  Would love to get this novel extension working.

installed gas-github v5.0.5 
Running Chrome v95.0.4638.69 (Official Build) (64-bit) on Windows 10 Pro
Using GAS IDE with new UI.

UPDATE - Working now - seemed to be a conflict with another extention.

**Comment by leonhartX** [comment]
Can you check the console log from developer tools? Is there any error?

**Comment by wmgillett** [comment]
I had checked that earlier error and saw this error
- 	DevTools failed to load source map: Could not load content for https://www.gstatic.com/monaco_editor/min-maps/vs/loader.js.map
This was cleared after I followed advice on stackoverflow
	Uncheck Enable JavaScript source maps and Enable CSS source map.

The errors now a several like these
- 	Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked! editor.main.js:83 
- 	[Report Only] This document requires 'TrustedScriptURL' assignment. /home/monaco/ulTIuVu4XElZ/worker.js:1
- 	[Report Only] This document requires 'TrustedScriptURL' assignment. workerMain.js:19

**Comment by wmgillett** [comment]
Good news - got it working by disabling other extensions (should have checked it before).  Not sure which one it might have conflicted with.  I had maybe 15-20 active.  I did see an authorization modal come up when I finally got it working.  That allowed all the repos to be displayed.
