### ISSUE TITLE
Files renamed in IDE are treated as new files and pushed to the repository

### ISSUE THREAD

**Issue by stardotbmp** [leonhartX/gas-github#17]
Any file rename in the IDE and then pushed is treated as a new file.

**Comment by leonhartX** [comment]
@stardotbmp same as #16 , this extension does not support file deleted or file name changed(described in feature).
This extension does not implement a git system in GAS, so it doesn't have any git's revision info to track filename changed or file deleted. What it does is just sync code based on filename.
Imagine that you have a `a.gs`, `b.gs` in both GAS and Github, then in GAS delete `a.gs` and create a new file `c.gs`, there is no way to tell it was a `rename` or just `delete` and `create` without revision info.
Maybe track the gwt call seems like a solution, but when the operation happens out of the extension (some GAS IDE without the extension)and back to extension, we are again in trouble.

If you have any idea to do with this, please tell me of PR, thanks!

**Comment by leonhartX** [comment]
file rename is supported from v2.0.0
