### ISSUE TITLE
bug : pull from gist resulting in f() is not a function

### ISSUE THREAD

**Issue by marekkalnik** [leonhartX/gas-github#28]
Hi,

first of all - thanks for this great extension ! :)

I have encountered a bug while pulling from a gist - after the "diff" screen I get an `f() is not a function` error and the code does not update.

The faulty line is `https://github.com/leonhartX/gas-github/blob/master/src/gas-api.js#L7`.
If there is no match (a file not ending in .gs or .html) `return;` returns undefined and results in `https://github.com/leonhartX/gas-github/blob/master/src/gas-api.js#L43` failing due to f() being undefined.

In my example I wanted to commit a .gitignore file and it didn't work.

I would suggesting either returning empty function or filtering the array to remove empty items to pull only compatible files and don't break on other. What do you think?

**Comment by leonhartX** [comment]
Thanks for the report!
>I would suggesting either returning empty function or filtering the array to remove empty items to pull only compatible files and don't break on other. What do you think?

Yes, that's sounds a good idea. I'll take some time to look at this.
Or if you can make a pull request that will be the best!

**Comment by leonhartX** [comment]
fixed with #30
