### ISSUE TITLE
Repository drop down only shows 30 results. 

### ISSUE THREAD

**Issue by Spencer-Easton** [leonhartX/gas-github#3]
Repository drop down only shows 30 results. The github api paginates the results and puts that in the Link element of the header.   
https://developer.github.com/v3/repos/#list-user-repositories

**Comment by leonhartX** [comment]
@Spencer-Easton thanks, I'll check the paginates and see how to work with it

**Comment by leonhartX** [comment]
Fixed in 0.1.2
Follow Link header to get all Repositories and Branches.

**Comment by Spencer-Easton** [comment]
Cheers looks great! Thank you.
