### ISSUE TITLE
[Enhancement] Support bitbucket 

### ISSUE THREAD

**Issue by DimuDesigns** [leonhartX/gas-github#31]
This is an awesome tool. However, github private repos are a pay-to-play service. Bitbucket offers private repos free of charge so it would be beneficial to have this tool support bitbucket repos as well.

**Comment by leonhartX** [comment]
Yes, I have considered this: #7, for now there's no api to commit code to bitbucket so it seems impossible.
For a workaround, you could use secret gist instead of repo.

**Comment by DimuDesigns** [comment]
Actually, Atlassian recently added support for commits:

https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/src#post

**Comment by leonhartX** [comment]
That's great!
I'll take some time to look at this, thanks for the information.

**Comment by DimuDesigns** [comment]
Cool!
 
I was thinking of forking your code and attempting it myself but I couldn't make sense of how the code was structured. It looks like you have a custom build process in place as the files don't appear to be laid out like a typical chrome extension.
 
In any case, this would be the perfect opportunity for you to use ES6 classes to abstract out a common interface and have separate github and bitbucket implementations of that interface. Let me know when you get started on this, I'd like to chip wherever possible.

**Comment by leonhartX** [comment]
A common interface will be a good idea, but maybe a little difficult to cover gist since it's something different from repos.
and actually I didn't use some build process, the javascript files under `src` is just the same as the work in the extension as content-script.

**Comment by DimuDesigns** [comment]
Noticed that you've added the enhancement tag...and that you've started to work on a common interface...so is it safe to assume that you're actively working on this feature?

**Comment by leonhartX** [comment]
Yes, I'm working on this, should be shipped out in next few weeks.

**Comment by leonhartX** [comment]
@DimuDesigns Hi, the bitbucket support is almost completed, but still need test to insure that really works.
I will make a release with the .crx file before upload to the store, so do you like to try that and help to test?

**Comment by DimuDesigns** [comment]
Awesome! 
It would be my pleasure to test your latest release!

---------------
Loaded up the CRX file locally and here are my findings.

Unfortunately I was not able to create a repo from the App Script editor but I was able to push content to an existing repo. 

Also you need to make the dialogs more context-sensitive by updating their texts; some of them reference github when they should be referencing bitbucket.

Great work so far! The only major issue I came across was not being able to create a repo. Fix that and make the dialogs context-sensitive and you're good to go!

**Comment by leonhartX** [comment]
Thanks! Can you describe the create repo issue in detail since I can not
reproduce.

**Comment by DimuDesigns** [comment]
Sure. Here are the steps I took:

- login using the bitbucket sign-in
- navigate to the repo drop-down
- select "Create new repo"
- a dialog opens titled "Create Github repository" (should be bitbucket)
- I filled out the form with Repository Name, Description and selected Type (tested both public and private) from the dropdown
- I receive the error message "Failed to create new repository"

**Comment by leonhartX** [comment]
@DimuDesigns What is the repo name you created? Did you filled with user/org name like leonhartX/some-repo?

**Comment by DimuDesigns** [comment]
@leonhartX I tried creating repos with and without a username prefix; neither worked :( .

Here's are the strings I tried:

- dimudesigns/testRepo25
- testRepo25
- DimuDesigns/testRepo25

**Comment by leonhartX** [comment]
Um, that's weird. It should work with the simple repo name without username (the login form's username is used), can you check your login name to make sure it's correct?
Since the username has nothing to do with login so typo won't be noticed, but the name will be used after login like create repo, etc.
Also, if you can open the chrome's developer tools' network panel to see which request get an error, that's will be much helpful!

Anyway, I'm trying to add full name repo creating support so you can create repo with single repo name(some-repo), it will be created under your own username by default, or a full name like some-org/some-repo to create it under the organization/username.

**Comment by leonhartX** [comment]
@DimuDesigns Hi, I have made some changes, now you can select the repo's owner(user or team) and just enter the repo name to create(also works with github orgs).
The crx file is updated in the pre-release, so please try this and give for your feedback.
Thanks!

**Comment by leonhartX** [comment]
supported in v3.0.0
