### ISSUE TITLE
Support Gitlab

### ISSUE THREAD

**Issue by leonhartX** [leonhartX/gas-github#32]
gitlab seems has api to create commit from the [doc](https://docs.gitlab.com/ce/api/commits.html#create-a-commit-with-multiple-files-and-actions)

**Comment by jrob256** [comment]
Really looking forward to Gitlab support, is there any estimate on when this will be available?

**Comment by leonhartX** [comment]
I'm planing to focus on this after bitbucket support released.
If gitlab.com does provide sufficient APIs which is needed, then this feature should be released in the next few weeks.
