### ISSUE TITLE
Can't log into Github any more from Apps Script editor w/ Github Assistant v3.0.1

### ISSUE THREAD

**Issue by jeffentre** [leonhartX/gas-github#41]
Hi LeonhartX.  I've got v3.0.1 of your excellent extension installed. But now when I open the script editor I have a warning message at the top saying, "Extension has been updated, please relogin  Dismiss." Clicking on the "Dismiss" link does nothing. It is dead. I do see that I'm not logged into Github any more in the editor so when I click the Assistant's button to "Login SCM," I get the following page: 
lfjcgcmkmjjlieihflfhjopckgpelofo is blocked

Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

I've logged out of Chrome.  I've logged out of Github.  I've logged out of Google.  I've disabled, removed, and reinstalled the Assistant extension. No other extensions seem relevant but I've disabled them all.  I've closed the browser entirely. Can you please help me figure out what I need to do to get back in?  I think the fact that the warning's "Dismiss" link is dead might be a clue, but not for me. :-(  Thx, - Jeff

**Comment by leonhartX** [comment]
This seems you have some adblock plugin that blocked the request, you can check [this post](https://stackoverflow.com/questions/22318119/i-am-getting-failed-to-load-resource-neterr-blocked-by-client-with-google-chr)
The dismiss link not work is a bug, but not relate to the login issue.

**Comment by leonhartX** [comment]
Also, if the login scm has been block, you can try the extension's option menu to login.
The Login SCM just open the menu's url in a new tab.

**Comment by jeffentre** [comment]
Thank you for your quick response!  The warning with the dismiss link is gone, and although I still couldn't log into github from the "Login SCM" button, which gave me that same error, I was able to log into Github with the options menu.  So I'm in now and I can see my repositories!  Thank you!
