### ISSUE TITLE
Bitbucket Connection

### ISSUE THREAD

**Issue by thomas-vl** [leonhartX/gas-github#45]
After i login with bitbucket it results in an unknown error.
Console error:
GET https://api.bitbucket.org/2.0/repositories/?access_token=....&access_token=...&q=...&role=contributor&access_token=undefined 401 ()
<img width="235" alt="screen shot 2017-10-11 at 09 59 11" src="https://user-images.githubusercontent.com/13116569/31428485-246ffc62-ae6b-11e7-976b-c5f9b773849b.png">

**Comment by leonhartX** [comment]
Hi, can you provide some more details?
And please check you bitbucket's oauth page whether `gas-github` has been authorized like this


![2017-10-11 17 37 43](https://user-images.githubusercontent.com/3993518/31430129-e9b0be1e-aeaa-11e7-8e76-e650adf1f1ef.png)

**Comment by thomas-vl** [comment]
Hi leonhartX,

Sure thing what kind of details do you need?

![screen shot 2017-10-12 at 09 30 34](https://user-images.githubusercontent.com/13116569/31484300-0c4d94a8-af30-11e7-9a95-f77dc61e6571.png)

**Comment by leonhartX** [comment]
Please first try revoke the integrated oauth and logout extension, then re-login, if still error, please get the error request detail with response from develop tool's network panel.
Thanks.

**Comment by pyrochlore** [comment]
Hi,
I have the same problem connecting to bitbucket server.

I have checked that the gas-github was added to OAuth integrated applications.
"gas-github | sync code from GAS to bitbucket | 2017-09-13T01:27:09.775180+00:00"

And from chrome developer console, I have this error
"Failed to load resource: the server responded with a status of 401 ()"
The actual response is {"type": "error", "error": {"message": "Access token expired. Use your refresh token to obtain a new access token."}}

Tried revoke and reinstalled extension but still error.

The request is something like https://api.bitbucket.org/2.0/repositories/?access_token=XXXXXXXXXX&access_token=XXXXXXXXXX&q=YYYYYYYYYY&after=2013-11-12T03.....&role=contributor&acccess_token=undefined

**Comment by leonhartX** [comment]
@pyrochlore thanks for the detail.
Before the error request, there should be a request to get access token like:
```
https://bitbucket.org/site/oauth2/access_token
```
can you check the response of that request? normally it should like this:
```
{"access_token": "xxx", "scopes": "repository:admin repository:write team account", "expires_in": 3600, "refresh_token": "yyy", "token_type": "bearer"}
```

**Comment by pyrochlore** [comment]
I got the response. Looks exactly the same as yours.
{"access_token": "xxx", "scopes": "repository:admin repository:write team account", "expires_in": 3600, "refresh_token": "yyy", "token_type": "bearer"}

I also found the apps tried to retrieve all information of all my repositories in few requests (because I have a lot).
The first two requests went well (each request contains ten repos) but the third request failed.
And they all share the same token.

Hope these will help.

**Comment by leonhartX** [comment]
Thanks!
>I also found the apps tried to retrieve information of all my repositories in few requests.

Yes, the extension will get all repos for list up in the repo binding menu, seems like there's something wrong with the paginate iterator.

**Comment by leonhartX** [comment]
release this in v3.2.2
