### ISSUE TITLE
Mixed case filenames in GAS project

### ISSUE THREAD

**Issue by TakashiSasaki** [leonhartX/gas-github#50]
Using mixed case filenames in GAS project causes strange behavior when push and pull.

0. Create new GAS project
1. Create a file, helloWorld.gs
2. Push GAS project to Github
3. Edit helloWorld.gs and rename it to helloworld.gs
4. Try push and pull.

**Comment by leonhartX** [comment]
This seems not related to gas-github but about cache.
After rename the file, the same api trying to get contents of the repo maybe cached by browser.

<img width="472" alt="screen shot 2017-11-20 at 16 58 59" src="https://user-images.githubusercontent.com/3993518/33007946-522dfb22-ce14-11e7-9e9b-252b4c08c5cc.png">

**Comment by TakashiSasaki** [comment]
I see. I'll try to reload entire page after renaming.

**Comment by leonhartX** [comment]
Reload page maybe not a solution since cache won't expired just by reload.
The cache-control in github's response is just 60 so you can simply wait 1 minute to let the cache expired.

**Comment by TakashiSasaki** [comment]
I understand. I take a coffee break. 😄
