### ISSUE TITLE
Unable to Push/Pull to Bitbucket

### ISSUE THREAD

**Issue by teckler** [leonhartX/gas-github#56]
I have had several commits over the last few weeks with no issue. Now when I try to push I get a "reject is not defined" error. I have reinstalled, reconnected, rebooted and tried in a new repository with no success.

**Comment by forstmeier** [comment]
I have encountered the same error with GitHub and I also attempted the same fix @teckler mentions. This started today (yesterday it was working perfectly).

**Comment by supertopoz** [comment]
Me too, when pushing or pulling to Git hub I get "reject is not defined" (Yesterday it was working perfectly).

**Comment by leonhartX** [comment]
Thanks for the report, seems GAS has some change it the PRC response, I'm working on it now.

**Comment by leonhartX** [comment]
v3.3.1 should fix this issue
