### ISSUE TITLE
[Blocker] Reject is not defined

### ISSUE THREAD

**Issue by sp-guillem-orpinell** [leonhartX/gas-github#59]
I've been using the assistant several months, yesterday was working properly.

Today, either 'Pull' and 'Push' triggers next error:
![screenshot 2018-02-08 11 47 58](https://user-images.githubusercontent.com/25321113/35969174-427fef64-0cc6-11e8-8e6b-f8a263839899.png)

My coworker tried it and he had the same issue. Anyone else having same issue?

It's a full blocker :(

**Comment by andrewroberts** [comment]
Go into Chrome > Settings > extensions and force a refresh. This has been fixed in 3.3.1.

**Comment by sp-guillem-orpinell** [comment]
Yeyy, it works! Thank you :)

I found this [step-by-step guide](https://www.howtogeek.com/64525/how-to-manually-force-google-chrome-to-update-extensions/) that could be useful for other users ;)
