### ISSUE TITLE
Pulling files that are .js instead of .gs are not fetched

### ISSUE THREAD

**Issue by rielzzapps** [leonhartX/gas-github#6]
Some libraries remove the .gs when updating to GitHub. Maybe it is easy to automatically put .gs behind them. Probably they choose .js to have GitHub format the file nicely.

**Comment by leonhartX** [comment]
Thanks for the report.
Fetch `.js` files and change to `.gs` in gas is very easy, but after this, push from gas will create same files with `.gs` in github and maybe this is not as expected.
I'll try some ways to see whether there has a better solution.

**Comment by rielzzapps** [comment]
I understand. You can never be sure if a .js file should become a .gs file
...
One could default all files to .gs EXCEPT the .html files?
I agree that saving them as .js in the first place is a bad practice, so I
am not sure if this is really an issue.

Riël Notermans
Zzapps B.V. • High Tech Campus 9, 5656 AE Eindhoven
<https://www.google.nl/maps/place/Zzapps/@51.4099441,5.4510368,16z/data=!4m5!1m2!3m1!2sZzapps!3m1!1s0x0000000000000000:0x3ad8d7839ef5a5dd>
T 040 711 41 94 <+31407114194> • E riel@zzapps.nl • www.zzapps.nl
WIJ MAKEN HET ONDENKBARE MOGELIJK

2016-10-16 15:18 GMT+02:00 Ke Xu <notifications@github.com>:

**Comment by leonhartX** [comment]
planing to add an option to enable using `.js` instead of `.gs`

**Comment by leonhartX** [comment]
fixed in 3.1.0 with an option to change filetype to sync
