### ISSUE TITLE
no code pushed, saying Everything already up-to-date

### ISSUE THREAD

**Issue by machinefriendly** [leonhartX/gas-github#60]
Hi, 

I may have same issue as this issue mentioned https://github.com/leonhartX/gas-github/issues/58, I created new repo and pushed, it shows "Everything already up-to-date" and no code pushed when I verify on github. 
I verified the known issues here https://github.com/leonhartX/gas-github#5known-issues, but my code file is not empty, while no function name is same as any file name, you have below screenshot with all functions' names and only one file.
![a](https://dha4w82d62smt.cloudfront.net/items/3e2K3X0Z2E3Z3Q1w4625/%5B166917304a4635400b95b7692cfe5f85%5D_09-02-2018%252014-45-42.jpg?X-CloudApp-Visitor-Id=66189&v=d6acdd80)

Thanks in advance for your help.

Best,

**Comment by machinefriendly** [comment]
@andrewroberts Thanks, but I login/logOut, cleaned browser cache, create new repo manually on github, it doesn't help.

**Comment by leonhartX** [comment]
are you opening multiple scripts in your browser?

**Comment by machinefriendly** [comment]
@leonhartX No, only one script window opened. 
I just tested again, and finally find the cause of the issue, it's due to the INSTALLABLE TRIGGER, after several new file/ script/gitRepo testings, what I find is that, if I set a installable trigger in script BEFORE the FIRST connect from that script to github, we'll be fail to synch with github, different issue performances:

* we are not able to push any code to github, no matter master or other branch. As screenshot in my previous update.
* we can push first version of code to master or branch, but the code change cannot be rightly recognized by add-on, but seen as DELETE script file action, below screenshot for your information:
![](https://dha4w82d62smt.cloudfront.net/items/1p2y0J0O21210y1C3j1f/Image%202018-02-10%20at%206.27.56%20PM.png?X-CloudApp-Visitor-Id=66189&v=cde75a28)

But the issue cannot be reproduced every time, it's confusing. Thanks in advance.

**Comment by edmiss** [comment]
Same issue. It suggest there is no file in GAS folder, if there is any old file in repo push will delete old files.

**Comment by edmiss** [comment]
I got same issue here, the only difference is I did not use any TRIGGER beside onOpen, and even if I delete the onOpen() it still has this issue. If I push, github simple delete every single file I have. (except readme.txt)

![capture](https://user-images.githubusercontent.com/18342222/36067743-693566c6-0e78-11e8-97c0-34f4ce132dc5.PNG)

**Comment by leonhartX** [comment]
Still can not reproduce this one.
Can you provide this RPC call in GAS with it's response?
```
https://script.google.com/d/${projectId}/gwt/ideService
```
you can filter from the `Network` tab like:
![2018-02-11 10 03 34](https://user-images.githubusercontent.com/3993518/36068198-ec332a96-0f12-11e8-82bb-836e02842037.png)

**Comment by leonhartX** [comment]
This is a bug relate to embedded script, v3.3.1 only fixed for standalone script.
v3.3.2 should fix this.

**Comment by machinefriendly** [comment]
Thanks a lot for quick update.
