### ISSUE TITLE
Access with the Personal access tokens I created not work

### ISSUE THREAD

**Issue by Wildfoot** [leonhartX/gas-github#77]
I created a Personal access tokens by myself and pasted it to the field and click login. and nothing happen.

**Comment by leonhartX** [comment]
for github or gitlab?

**Comment by leonhartX** [comment]
also please make sure your token has the correct permission(for github, the repo and `gist`, for `gitlab`, the `api`)

**Comment by Wildfoot** [comment]
I'm using GitHub. And I'm pretty sure the permission is correct. Like below:
![image](https://user-images.githubusercontent.com/11520473/38564637-216331d4-3d12-11e8-9663-490242b251a3.png)
And when I click "GITHUB LOGIN", It didn't give me any respond.
![image](https://user-images.githubusercontent.com/11520473/38564668-31de2dde-3d12-11e8-8bfb-64be22e3cdd0.png)
p.s. use username and password is working for me, I just want to told you that issue.

**Comment by leonhartX** [comment]
You still need to enter the username even using access token.

**Comment by Wildfoot** [comment]
My fault.
