### ISSUE TITLE
Icon/Promo Image wanted

### ISSUE THREAD

**Issue by leonhartX** [leonhartX/gas-github#89]
Sadly because the lack of design skills for myself, it's hard to improve the currently ugly stuffs. 
So I'll be very appreciate if anyone can design a better icon/promotion image for this extension 😄

**Comment by klausrheum** [comment]
How about something like this?

![image](https://user-images.githubusercontent.com/45514331/49363296-e6989a00-f713-11e8-87ac-f30f0860c6bf.png)

Mocked up in Google Drawings - I can share you the doc but you can probably make something cleaner in Inkscape. I only have a Chromebook here!
