### ISSUE TITLE
Pull / Push more than one gs not working as expecte

### ISSUE THREAD

**Issue by ststolz** [leonhartX/gas-github#91]
The plugin works when only working with one gs file. When I try to add a second one, it is pushes correctly. But when I make changes and push again, I get an error and it is not pushed. When I try to pull, the plugin wants to delete this file. When I delete it, I can push again, but then I run in the same problem.

From this I think the problem is: For some reason the plugin can not recognize more than one gs file in the repo. 

I am using a GitLab Repo.

**Comment by leonhartX** [comment]
Please check the known issue first
