### ISSUE TITLE
Repo does not get saved in the cache

### ISSUE THREAD

**Issue by sp-guillem-orpinell** [leonhartX/gas-github#95]
On select a repo and reload the page, I need to select the repo again.  Also, on reopening an script, the repo doesn't have been saved in the cache.

At my company we have hundreds of repos, so the experience is annoying to look for the repo every time :/

My colleague does not have this issue. And I didn't have it 6 months ago, so I'm not sure what could be... Posting the issue to see if someone could help to find the problem.

**Comment by leonhartX** [comment]
This config is saved in the chrome's local storage, maybe some configuration of your browser prevent the extension to write storage

**Comment by sp-guillem-orpinell** [comment]
Thanks @leonhartX ! Now is working properly :) I added scripts.google.com to the Adblock whitelist, and uninstall and install again the extension; I guess one of those (or both) helped to fix the issue!
